[package]
name = "specta-macros"
description = "Macros for specta. Don't use directly!"
version = "1.1.0+frk.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/specta"
documentation = "https://docs.rs/specta/latest/specta"
keywords = ["async", "specta", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

publish = ["elleci"]

[features]
serde = ["termcolor"]
export = []

[lib]
proc-macro = true

[dependencies]
Inflector = { version = "0.11", default-features = false }
itertools = "0.15"
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
termcolor = { version = "1.1", optional = true }
